[package]
name = "ssh-mesh-crate"
version = "0.0.1"
edition = "2021"

[dependencies]
jni = "0.21.1"
jni-sys = "0.3.0"
nix = { version = "0.29.0", features = ["socket", "process"] }
libc = "0.2.161"
openssl = { version = "0.10", features = ["vendored"] }
libffi = "5.0.0"
libffi-sys = "4.0.0"
bytes = "1"
futures = "0.3"
anyhow = "1.0.48"
libloading = "0.9"
regex = "1.5"
log = "0.4.26"
async-trait = "0.1"
rustix = { version = "0.38.32", features = ["libc", "fs", "alloc", "event", "libc_errno", "mm", "std", "use-libc", "use-libc-auxv"] }
ctrlc = "3.2.1"
serde={version="1.0.130", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.9.11"
tokio = { version = "1", default-features = false, features = ["rt", "rt-multi-thread", "macros", "time", "sync"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing = "0.1"
mio = { version = "0.8", features = ["os-poll", "os-ext"] }
clap = { version = "4.0", features = ["derive"] }
hyper = {version = "1.8", default-features = false, features = ["http1", "http2", "server", "client"] }
hyper-util = { version = "0.1", default-features = false, features = ["tokio", "server", "http1", "http2"] }
hyper-tls = "0.6.0"
rand = { version = "0.8", optional = true }
env_logger = "0.10"
http = "1.4.0"
http-body-util = "0.1.3"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
russh = { version = "0.55.0", default-features = false, features = ["ring"], optional = true}
russh-keys = {version = "0.49.2", optional = true}
ssh-key = { version = "0.6.7", optional = true }
ed25519-dalek = { version = "2.0", optional = true }
base64 = { version = "0.21", optional = true }
embedded-io = { version = "0.6", optional = true, features = ["std"] }
embedded-io-async = { version = "0.6", optional = true, features = ["std"] }
russhd = { path = "../russhd", optional = true }
pmond = { path = "../pmond", optional = true }
lmesh = { path = "../lmesh" }
echo_service = { path = "../echo_service" }

[dev-dependencies]
tempfile = "3.3"

#[target.'cfg(target_env = "musl")']
#rustflags = ["-C", "target-feature=+crt-static"]

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
overflow-checks = false

[profile.releasesize]
inherits = "release"
# RUSTFLAGS="-C opt-level=z -C lto=fat -C codegen-units=1 -C panic=abort -C strip=symbols" cargo build --release -p ssh-mesh
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
overflow-checks = false
