[package]
name = "pmond"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pmond"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.48"
log = "0.4.26"
tracing = "0.1"
tokio = { version = "1", features = ["net", "sync", "io-util", "rt", "macros", "fs", "rt-multi-thread", "tracing", "sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nix = { version = "0.29.0", features = ["socket", "process"] }
libc = "0.2.161"
mio = { version = "0.8", features = ["os-poll", "os-ext"] }
hyper = { version = "1.8.1", default-features = false, features = ["http1", "http2", "server", "client"] }
hyper-util = { version = "0.1", default-features = false, features = ["tokio", "server", "http1", "http2"] }
http-body-util = "0.1.3"
bytes = "1"
fastwebsockets = { version = "0.10.0", features = ["upgrade"] }
futures-util = "0.3"
tracing-subscriber = "0.3"
env_logger = "0.10"
tokio-util = { version = "0.7", features = ["io", "compat"] }
users = "0.11"
ws = { path = "../ws" }
axum = "0.7"
tower-http = { version = "0.5", features = ["fs"] }

[dev-dependencies]
tempfile = "3.3"
